use_frameworks!

platform :ios, '10.0'

target 'JKPacket_Example' do
  pod 'JKPacket', :path => '../'
  pod 'SnapKit', '~> 5.0.0'


  target 'JKPacket_Tests' do
    inherit! :search_paths

    #pod 'Quick', '~> 2.2.0'
    #pod 'Nimble', '~> 8.0.7'
  end
end
